document.addEventListener('DOMContentLoaded', () => {
    // Exemple d'items à stocker
    const items = [
        { id: 1, name: "minor healing potion", image: "minorHealingPotion.jpeg", cost: 10, category: "petit objet" },
        { id: 2, name: "minor-cure-potion", image: "minor-cure-potion.jpeg", cost: 10, category: "petit objet" },
        { id: 3, name: "minor-mana-potion", image: "minor-mana-potion.jpeg", cost: 10, category: "petit objet" },
        { id: 4, name: "minor-power-potion", image: "minor-power-potion.jpeg", cost: 10, category: "petit objet" },
        { id: 5, name: "minor-stamina-potion", image: "minor-stamina-potion.jpeg", cost: 10, category: "petit objet" },
        { id: 6, name: "steel-ring", image: "steel-ring.jpeg", cost: 20, category: "petit objet" },
        { id: 7, name: "Stun-powder", image: "Stun-powder.jpeg", cost: 20, category: "petit objet" },
        { id: 8, name: "moon-earring", image: "moon-earring.jpeg", cost: 20, category: "petit objet" },
        { id: 9, name: "resonant-crystal", image: "resonant-crystal.jpeg", cost: 20, category: "petit objet" },
        { id: 10, name: "minor-antidote", image: "minor-antidote.jpeg", cost: 25, category: "petit objet" },
        { id: 11, name: "Dampening ring", image: "dampening-ring.jpeg", cost: 25, category: "petit objet" },
        { id: 12, name: "ring-of-haste", image: "ring-of-haste.jpeg", cost: 30, category: "petit objet" },
        { id: 13, name: "major-stamina-potion", image: "major-stamina-potion.jpeg", cost: 30, category: "petit objet" },
        { id: 14, name: "scroll-of-haste", image: "scroll-of-haste.jpeg", cost: 30, category: "petit objet" },
        { id: 15, name: "major-cure-potion", image: "major-cure-potion.jpeg", cost: 30, category: "petit objet" },
        { id: 16, name: "scroll-of-healing", image: "scroll-of-healing.jpeg", cost: 30, category: "petit objet" },
        { id: 17, name: "major-healing-potion", image: "major-healing-potion.jpeg", cost: 30, category: "petit objet" },
        { id: 18, name: "scroll-of-power", image: "scroll-of-power.jpeg", cost: 30, category: "petit objet" },
        { id: 19, name: "major-mana-potion", image: "major-mana-potion.jpeg", cost: 30, category: "petit objet" },
        { id: 20, name: "ring-of-brutality", image: "ring-of-brutality.jpeg", cost: 40, category: "petit objet" },
        { id: 21, name: "Doom powder", image: "doom-powder.jpeg", cost: 40, category: "petit objet" },
        { id: 22, name: "remote-spider", image: "remote-spider.jpeg", cost: 40, category: "petit objet" },
        { id: 23, name: "sun-earring", image: "sun-earring.jpeg", cost: 40, category: "petit objet" },
        { id: 24, name: "major-power-potion", image: "major-power-potion.jpeg", cost: 40, category: "petit objet" },
        { id: 25, name: "super-healing-potion", image: "super-healing-potion.jpeg", cost: 50, category: "petit objet" },
        { id: 26, name: "falcon figurine", image: "falcon-figurine.jpeg", cost: 50, category: "petit objet" },
        { id: 27, name: "Doomed compass", image: "doomed-compass.jpeg", cost: 50, category: "petit objet" },
        { id: 28, name: "ring-of-duality", image: "ring-of-duality.jpeg", cost: 50, category: "petit objet" },
        { id: 29, name: "Curious gear", image: "curious-gear.jpeg", cost: 50, category: "petit objet" },
        { id: 30, name: "rift-device", image: "rift-device.jpeg", cost: 50, category: "petit objet" },
        { id: 31, name: "major-antidote", image: "major-antidote.jpeg", cost: 50, category: "petit objet" },
        { id: 32, name: "ring-of-skulls", image: "ring-of-skulls.jpeg", cost: 50, category: "petit objet" },
        { id: 33, name: "Helix ring", image: "helix-ring.jpeg", cost: 50, category: "petit objet" },
        { id: 34, name: "smoke-elixir", image: "smoke-elixir.jpeg", cost: 50, category: "petit objet" },
        { id: 35, name: "phasing-idol", image: "phasing-idol.jpeg", cost: 50, category: "petit objet" },
        { id: 36, name: "scroll-of-stamina", image: "scroll-of-stamina.jpeg", cost: 50, category: "petit objet" },
        { id: 37, name: "Black censer", image: "black-censer.jpeg", cost: 50, category: "petit objet" },
        { id: 38, name: "utility-belt", image: "utility-belt.jpeg", cost: 50, category: "petit objet" },
        { id: 39, name: "volatile-elixir", image: "volatile-elixir.jpeg", cost: 50, category: "petit objet" },
        { id: 40, name: "Giant remote spider", image: "giant-remote-spider.jpeg", cost: 60, category: "petit objet" },
        { id: 41, name: "Lucky eye", image: "lucky-eye.jpeg", cost: 60, category: "petit objet" },
        { id: 42, name: "Heart of the betrayer", image: "heart-of-the-betrayer.jpeg", cost: 60, category: "petit objet" },
        { id: 43, name: "star-earring", image: "star-earring.jpeg", cost: 70, category: "petit objet" },
        { id: 44, name: "Black card", image: "black-card.jpeg", cost: 75, category: "petit objet" },
        { id: 45, name: "power-core", image: "power-core.jpeg", cost: 75, category: "petit objet" },
        { id: 46, name: "second-chance-ring", image: "second-chance-ring.jpeg", cost: 75, category: "petit objet" }, 
        { id: 47, name: "winged-shoes", image: "winged-shoes.jpeg", cost: 20, category: "jambe" },
        { id: 48, name: "heavy-greaves", image: "heavy-greaves.jpeg", cost: 20, category: "jambe" },
        { id: 49, name: "boots-of-striding", image: "boots-of-striding.jpeg", cost: 20, category: "jambe" },
        { id: 50, name: "boots-of-speed", image: "boots-of-speed.jpeg", cost: 30, category: "jambe" },
        { id: 51, name: "comfortable-shoes", image: "comfortable-shoes.jpeg", cost: 30, category: "jambe" },
        { id: 52, name: "rejuvenation-greaves", image: "rejuvenation-greaves.jpeg", cost: 35, category: "jambe" },
        { id: 53, name: "boots-of-dashing", image: "boots-of-dashing.jpeg", cost: 40, category: "jambe" },
        { id: 54, name: "endurance-footwraps", image: "endurance-footwraps.jpeg", cost: 40, category: "jambe" },
        { id: 55, name: "boots-of-levitation", image: "boots-of-levitation.jpeg", cost: 50, category: "jambe" },
        { id: 56, name: "shoes-of-happiness", image: "shoes-of-happiness.jpeg", cost: 50, category: "jambe" },
        { id: 57, name: "drakescale-boots", image: "drakescale-boots.jpeg", cost: 50, category: "jambe" },
        { id: 58, name: "magma-waders", image: "magma-waders.jpeg", cost: 50, category: "jambe" },
        { id: 59, name: "elemental-boots", image: "elemental-boots.jpeg", cost: 50, category: "jambe" },
        { id: 60, name: "steel-sabatons", image: "steel-sabatons.jpeg", cost: 60, category: "jambe" },
        { id: 61, name: "boots-of-quickness", image: "boots-of-quickness.jpeg", cost: 75, category: "jambe" },
        { id: 62, name: "boots-of-sprinting", image: "boots-of-sprinting.jpeg", cost: 75, category: "jambe" },
        { id: 63, name: "serene-sandals", image: "serene-sandals.jpeg", cost: 75, category: "jambe" },
        { id: 64, name: "rocket-boots", image: "rocket-boots.jpeg", cost: 80, category: "jambe" },

        { id: 65, name: "weighted-net", image: "weighted-net.jpeg", cost: 20, category: "deux mains" },
        { id: 66, name: "ancient-drill", image: "ancient-drill.jpeg", cost: 30, category: "deux mains" },
        { id: 67, name: "war-hammer", image: "war-hammer.jpeg", cost: 30, category: "deux mains" },
        { id: 68, name: "long-spear", image: "long-spear.jpeg", cost: 30, category: "deux mains" },
        { id: 69, name: "piercing-bow", image: "piercing-bow.jpeg", cost: 30, category: "deux mains" },
        { id: 70, name: "ancient-bow", image: "ancient-bow.jpeg", cost: 40, category: "deux mains" },
        { id: 71, name: "hooked-chain", image: "hooked-chain.jpeg", cost: 40, category: "deux mains" },
        { id: 72, name: "reaping-scythe", image: "reaping-scythe.jpeg", cost: 40, category: "deux mains" },
        { id: 73, name: "basin-of-prophecy", image: "basin-of-prophecy.jpeg", cost: 50, category: "deux mains" },
        { id: 74, name: "masters-lute", image: "masters-lute.jpeg", cost: 50, category: "deux mains" },
        { id: 75, name: "skullbane-axe", image: "skullbane-axe.jpeg", cost: 50, category: "deux mains" },
        { id: 76, name: "staff-of-command", image: "staff-of-command.jpeg", cost: 50, category: "deux mains" },
        { id: 77, name: "staff-of-elements", image: "staff-of-elements.jpeg", cost: 50, category: "deux mains" },
        { id: 78, name: "staff-of-xorn", image: "staff-of-xorn.jpeg", cost: 50, category: "deux mains" },
        { id: 79, name: "mountain-hammer", image: "mountain-hammer.jpeg", cost: 50, category: "deux mains" },
        { id: 80, name: "elemental-claymore", image: "elemental-claymore.jpeg", cost: 50, category: "deux mains" },
        { id: 81, name: "staff-of-eminence", image: "staff-of-eminence.jpeg", cost: 60, category: "deux mains" },
        { id: 82, name: "wall-shield", image: "wall-shield.jpeg", cost: 60, category: "deux mains" },
        { id: 83, name: "staff-of-summoning", image: "staff-of-summoning.jpeg", cost: 60, category: "deux mains" },
        { id: 84, name: "halberd", image: "halberd.jpeg", cost: 75, category: "deux mains" },

        { id: 85, name: "battle-axe", image: "battle-axe.jpeg", cost: 20, category: "une main" },
        { id: 86, name: "heater-shield", image: "heater-shield.jpeg", cost: 20, category: "une main" },
        { id: 87, name: "fueled-falchion", image: "fueled-falchion.jpeg", cost: 20, category: "une main" },
        { id: 88, name: "poison-dagger", image: "poison-dagger.jpeg", cost: 20, category: "une main" },
        { id: 89, name: "black-knife", image: "black-knife.jpeg", cost: 25, category: "une main" },
        { id: 90, name: "versatile-dagger", image: "versatile-dagger.jpeg", cost: 25, category: "une main" },
        { id: 91, name: "volatile-bomb", image: "volatile-bomb.jpeg", cost: 30, category: "une main" },
        { id: 92, name: "wand-of-brilliance", image: "wand-of-brilliance.jpeg", cost: 30, category: "une main" },
        { id: 93, name: "wand-of-darkness", image: "wand-of-darkness.jpeg", cost: 30, category: "une main" },
        { id: 94, name: "wand-of-frost", image: "wand-of-frost.jpeg", cost: 30, category: "une main" },
        { id: 95, name: "wand-of-infernos", image: "wand-of-infernos.jpeg", cost: 30, category: "une main" },
        { id: 96, name: "wand-of-storms", image: "wand-of-storms.jpeg", cost: 30, category: "une main" },
        { id: 97, name: "wand-of-tremors", image: "wand-of-tremors.jpeg", cost: 30, category: "une main" },
        { id: 98, name: "brilliant-blade", image: "brilliant-blade.jpeg", cost: 30, category: "une main" },
        { id: 99, name: "frigid-blade", image: "frigid-blade.jpeg", cost: 30, category: "une main" },
        { id: 100, name: "night-blade", image: "night-blade.jpeg", cost: 30, category: "une main" },
        { id: 101, name: "storm-blade", image: "storm-blade.jpeg", cost: 30, category: "une main" },
        { id: 102, name: "jagged-sword", image: "jagged-sword.jpeg", cost: 30, category: "une main" },
        { id: 103, name: "inferno-blade", image: "inferno-blade.jpeg", cost: 30, category: "une main" },
        { id: 104, name: "tremor-blade", image: "tremor-blade.jpeg", cost: 30, category: "une main" },
        { id: 105, name: "throwing-axe", image: "throwing-axe.jpeg", cost: 35, category: "une main" },
        { id: 106, name: "spiked-shield", image: "spiked-shield.jpeg", cost: 40, category: "une main" },
        { id: 107, name: "bloody-axe", image: "bloody-axe.jpeg", cost: 40, category: "une main" },
        { id: 108, name: "tower-shield", image: "tower-shield.jpeg", cost: 40, category: "une main" },
        { id: 109, name: "unstable-explosives", image: "unstable-explosives.jpeg", cost: 45, category: "une main" },
        { id: 110, name: "cutpurse-dagger", image: "cutpurse-dagger.jpeg", cost: 45, category: "une main" },
        { id: 111, name: "focusing-ray", image: "focusing-ray.jpeg", cost: 50, category: "une main" },
        { id: 112, name: "imposing-blade", image: "imposing-blade.jpeg", cost: 50, category: "une main" },
        { id: 113, name: "orb-of-dawn", image: "orb-of-dawn.jpeg", cost: 50, category: "une main" },
        { id: 114, name: "orb-of-twilight", image: "orb-of-twilight.jpeg", cost: 50, category: "une main" },
        { id: 115, name: "silent-stiletto", image: "silent-stiletto.jpeg", cost: 50, category: "une main" }, 
        { id: 116, name: "skull-of-hatred", image: "skull-of-hatred.jpeg", cost: 50, category: "une main" },
        { id: 117, name: "psychic-knife", image: "psychic-knife.jpeg", cost: 50, category: "une main" },
        { id: 118, name: "sun-shield", image: "sun-shield.jpeg", cost: 50, category: "une main" },
        { id: 119, name: "sword-of-the-sands", image: "sword-of-the-sands.jpeg", cost: 50, category: "une main" },
        { id: 120, name: "balanced-blade", image: "balanced-blade.jpeg", cost: 60, category: "une main" },


        { id: 121, name: "flea-bitten-shawl", image: "flea-bitten-shawl.jpeg", cost: 10, category: "corps" },
        { id: 122, name: "hide-armor", image: "hide-armor.jpeg", cost: 10, category: "corps" },
        { id: 123, name: "chainmail", image: "chainmail.jpeg", cost: 20, category: "corps" },
        { id: 124, name: "leather-armor", image: "leather-armor.jpeg", cost: 20, category: "corps" },
        { id: 125, name: "cloak-of-invisibility", image: "cloak-of-invisibility.jpeg", cost: 20, category: "corps" },
        { id: 126, name: "cloak-of-pockets", image: "cloak-of-pockets.jpeg", cost: 20, category: "corps" },
        { id: 127, name: "second-skin", image: "second-skin.jpeg", cost: 30, category: "corps" },
        { id: 128, name: "shadow-armor", image: "shadow-armor.jpeg", cost: 30, category: "corps" },
        { id: 129, name: "studded-leather", image: "studded-leather.jpeg", cost: 30, category: "corps" },
        { id: 130, name: "splintmail", image: "splintmail.jpeg", cost: 35, category: "corps" },
        { id: 131, name: "swordedge-armor", image: "swordedge-armor.jpeg", cost: 40, category: "corps" },
        { id: 132, name: "robes-of-summoning", image: "robes-of-summoning.jpeg", cost: 40, category: "corps" },
        { id: 133, name: "robes-of-evocation", image: "robes-of-evocation.jpeg", cost: 40, category: "corps" },
        { id: 134, name: "blinking-cape", image: "blinking-cape.jpeg", cost: 50, category: "corps" },
        { id: 135, name: "cloak-of-the-hunter", image: "cloak-of-the-hunter.jpeg", cost: 50, category: "corps" },
        { id: 136, name: "doctors-coat", image: "doctors-coat.jpeg", cost: 50, category: "corps" },
        { id: 137, name: "drakescale-armor", image: "drakescale-armor.jpeg", cost: 50, category: "corps" },
        { id: 138, name: "platemail", image: "platemail.jpeg", cost: 50, category: "corps" },
        { id: 139, name: "steam-armor", image: "steam-armor.jpeg", cost: 50, category: "corps" },
        { id: 140, name: "sacrificial-robes", image: "sacrificial-robes.jpeg", cost: 50, category: "corps" },
        { id: 141, name: "cloak-of-phasing", image: "cloak-of-phasing.jpeg", cost: 75, category: "corps" },
        { id: 142, name: "curseward-armor", image: "curseward-armor.jpeg", cost: 75, category: "corps" },
        { id: 143, name: "iron-helmet", image: "iron-helmet.jpeg", cost: 10, category: "tete" },
        { id: 144, name: "amulet-of-life", image: "amulet-of-life.jpeg", cost: 20, category: "tete" },
        { id: 145, name: "telescopic-lens", image: "telescopic-lens.jpeg", cost: 20, category: "tete" },
        { id: 146, name: "hawk-helm", image: "hawk-helm.jpeg", cost: 20, category: "tete" },
        { id: 147, name: "circlet-of-elements", image: "circlet-of-elements.jpeg", cost: 25, category: "tete" },
        { id: 148, name: "heavy-basinet", image: "heavy-basinet.jpeg", cost: 30, category: "tete" },
        { id: 149, name: "eagle-eye-goggles", image: "eagle-eye-goggles.jpeg", cost: 30, category: "tete" },
        { id: 150, name: "horned-helm", image: "horned-helm.jpeg", cost: 30, category: "tete" },
        { id: 151, name: "chain-hood", image: "chain-hood.jpeg", cost: 40, category: "tete" },
        { id: 152, name: "necklace-of-teeth", image: "necklace-of-teeth.jpeg", cost: 40, category: "tete" },
        { id: 153, name: "empowering-talisman", image: "empowering-talisman.jpeg", cost: 45, category: "tete" },
        { id: 154, name: "drakescale-helm", image: "drakescale-helm.jpeg", cost: 50, category: "tete" },
        { id: 155, name: "helm-of-the-mountain", image: "helm-of-the-mountain.jpeg", cost: 50, category: "tete" },
        { id: 156, name: "horned-helm", image: "horned-helm.jpeg", cost: 50, category: "tete" },
        { id: 157, name: "telescopic-lens", image: "telescopic-lens.jpeg", cost: 50, category: "tete" },
        { id: 158, name: "mask-of-death", image: "mask-of-death.jpeg", cost: 50, category: "tete" },
        { id: 159, name: "mask-of-terror", image: "mask-of-terror.jpeg", cost: 50, category: "tete" },
        { id: 160, name: "stone-charm", image: "stone-charm.jpeg", cost: 50, category: "tete" },
        { id: 161, name: "pendant-of-the-plague", image: "pendant-of-the-plague.jpeg", cost: 50, category: "tete" },
        { id: 162, name: "protective-charm", image: "protective-charm.jpeg", cost: 60, category: "tete" },
        { id: 163, name: "pendant-of-dark-pacts", image: "pendant-of-dark-pacts.jpeg", cost: 75, category: "tete" },
        { id: 164, name: "crystal-tiara", image: "crystal-tiara.jpeg", cost: 75, category: "tete" },
    ];


  

    // Exemple de données du joueur à stocker
    const player = {
        gold: 10,
        items: []
    };

    // Stockez les données du joueur dans le localStorage si ce n'est pas déjà fait
    if (!localStorage.getItem('playerData')) {
        localStorage.setItem('playerData', JSON.stringify(player));
    }

    window.storeItems = items;
});
